### PR TITLE
[Hacktoberfest] Replace android views with compat

### PR DESCRIPTION
**Pull request by antoxa2584x**
Also code refactor

### CODE REVIEW

**Comment by krokyze** [comment]
Hi,

I tried to reach you by email, but with no luck. First of all, thank you for the pull request.

But I'm trying to keep as fewer changes as possible in the code written by developers from Yalantis so it would be easier for me to pull new changes. That's why I'm closing your pull request.

But you can definitely pull it here: https://github.com/Yalantis/uCrop

**Comment by jonasN5** [comment]
Could you pull update from the main repository? Yalantis made some important changes, especially for Android 10!

**Comment by krokyze** [comment]
> Could you pull update from the main repository? Yalantis made some important changes, especially for Android 10!

Done.

**Comment by jonasN5** [comment]
Thnx, after some further testing, it seems the Ucrop native version has
some problems with .webp files, which cannot be read.
Therefore, I need to create a non-native branch (I've tested .webp files
successfully on it) which include your own commits. How would you suggest
to proceed?

**Comment by jonasN5** [comment]
Hi,

since I know you don't really work with the lib anymore, I created a non
native version merging your work with uCrop. If you want, you could link it
on your repo for potential other users that had the same issue as me.
Anyways, thnx a lot for your work, it's greatly appreciated!

https://github.com/themadmrj/UcropWEdit

Best,

J.

**Comment by krokyze** [comment]
Hey @themadmrj can you make a pull request? I will add it in separate branch and release it 😉

**Pull request closed without merging**
